# This is a basic workflow to help you get started with Actions

name: stable-merge

# Controls when the workflow will run
# This will only run when a branch is merged into main
on:
  pull_request:
    branches: [ "main" ]
    types: [ "closed" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  on_merge:
    # only run jobs when we successfully merged our PR to main
    if: github.event.pull_request.merged == true
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Updates stable branch to from main branch
      - name: update-stable
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git fetch
          git checkout main-stable
          git merge main --allow-unrelated-histories
          git commit --amend -m "updating stable"
          git push origin main-stable
